#!/usr/bin/env bash

# This is the pre-commit hook I use, provided for sake of other users here
# It includes one check (viz., Dhall typechecking) and a perl one-liner to
# update the repository's linecount

set -e
# cabal new-run cpkg -- check-set pkgs/pkg-set.dhall
cabal new-test
perl -0777 -i -pe 's/```\n----.*```/```\n'"$(poly -c)"'\n```/igs' README.md
